server           {

		listen 127.0.0.1:8080; ##test #pp
		client_max_body_size	10M; #bob test ceci
		#test1 ;test2;test3;
		error_page 404	/errors/404.html;
		error_page 500	/errors/500.html;


	}

#fichier de config dedies a nos mamans
