server {
	listen 4242; # pour le tester de l'ecole
	client_max_body_size 100;

# Requirement 1: / must answer to GET request ONLY
	location / {
		root sources/www;
		methods GET;
		index index.html;
		# autoindex on;
	}

# Requirement 2: .bla must call the cgi_test executable
	location .bla {
		methods POST;
		cgi_pass .bla ./tech-stack/tests/script/cgi_tester;
	}

# Requirement 3: /post_body must answer anything to POST
	location post_body/ {
		methods POST;
		root sources/www;
	}

# Requirement 4: /directory/ GET, root YoupiBanane, index youpi.bad_extension
	location directory/ {
		methods GET;
		root .; # (See the explanation below why this is ./)
        index youpi.bad_extension;
	}
}