server {
	listen 8080;
	server_name test.com grifter.next;

	location / { # on peut mettre combien d'arguments/parametres dans la directive location ?
		root sources/www;
		methods GET POST DELETE;
		index index.html;
		error_page 404 404.html;
	}
  
}

server {
	listen 8081;
	server_name test.com grifter.next;

	location / { # on peut mettre combien d'arguments/parametres dans la directive location ?
		root tech-stack/www;
		methods GET;
		index index.html;
		error_page 404 404.html;
	}

}

server {
	listen 9292;
	server_name test.com grifter.next;

	location / { # on peut mettre combien d'arguments/parametres dans la directive location ?
		root sources/www;
		methods GET ;
		index index.html;
		error_page 404 404.html;
	}

}
