server {
	listen 8080;
	client_max_body_size 400;

	location / {
		root ./static/www;
		methods POST GET;
    	autoindex on;
		index index.html;
		error_page 404 404.html;

		cgi_pass .sh /usr/bin/bash;
	}

  location upload/ {
		root ./static/www;
    	autoindex on;
		methods GET POST DELETE;
		cgi_pass .py /usr/bin/python3;
	}

  location cgi-bin {
	root static/www/;
	methods POST GET;
	    autoindex on;
	error_page 504 504.html;


	cgi_pass .py /usr/bin/python3;
	cgi_pass .php /usr/bin/php-cgi;

  }

  location 42 {
	redirect 301 https://42.fr;
  }

  location here {
	redirect 302 /redirect.html;
  }


}

# SAME FRONT DIFFERENT BEHAVIOR
server {
	listen 9292;
	client_max_body_size 80M;

	location / {
		root static/www;
		methods GET POST;
		autoindex on;
		index nexsitepas.html;
		error_page 404 404.html;
	}

  location upload/ {
		root static/www;
		methods POST;
		autoindex off;
		#index HelloWord.html;
		error_page 404 404.html;
	}


}

# SECOND FRONT
server {
	listen 8081;

	location / {
		root static/www2;
		methods GET;
		error_page 404 404.html;
	}

}
