server {
	listen 8080;

	location / { # on peut mettre combien d'arguments/parametres dans la directive location ?
		root sources/www;
		methods GET;
    autoindex on;
		index index.html;
		error_page 404 404.html;
		error_page 504 504.html;

		cgi_pass .sh /usr/bin/bash;
	}

  location upload/ { # on peut mettre combien d'arguments/parametres dans la directive location ?
		root sources/www;
		methods GET POST DELETE;
		cgi_pass .py /usr/bin/python3;
	}

  location cgi-bin {
	root sources/www;
	methods POST GET;
	    # autoindex on;

	cgi_pass .py /usr/bin/python3;
	cgi_pass .php /usr/bin/php-cgi;

  }

  location repo {
	root sources/www/dossier;
	autoindex off;
	methods GET;
  }

}

server {
	listen 9292;
	client_max_body_size 10;

	location / { # on peut mettre combien d'arguments/parametres dans la directive location ?
		root sources/www;
		methods GET ;
		index index.html;
		error_page 404 404.html;
	}

  location upload/ { # on peut mettre combien d'arguments/parametres dans la directive location ?
		root sources/www;
		methods POST;
		autoindex on;
		index HelloWord.html;
		error_page 404 404.html;
	}


}

server {
	listen 8081;

	location / { # on peut mettre combien d'arguments/parametres dans la directive location ?
		root tech-stack/www;
		methods GET;
		error_page 404 404.html;
	}

}


server {
	listen 4242; # pour le tester de l'ecole
	client_max_body_size 100;

# Requirement 1: / must answer to GET request ONLY
	location / {
		root sources/www;
		methods GET;
		index index.html;
		# autoindex on;
	}

# Requirement 2: .bla must call the cgi_test executable
	location .bla {
		methods POST;
		cgi_pass .bla ./tech-stack/tests/script/cgi_tester;
	}

# Requirement 3: /post_body must answer anything to POST
	location post_body/ {
		methods POST;
		root sources/www;
	}

# Requirement 4: /directory/ GET, root YoupiBanane, index youpi.bad_extension
	location directory/ {
		methods GET;
		root .; # (See the explanation below why this is ./)
        index youpi.bad_extension;
	}
}
