server {
	listen 8080;

	location / {
		root static/www;
		methods GET POST DELETE;
    autoindex on;
		index /index.html;
		error_page 404 404.html;
	}

  location files/ {
		root static/www;
    methods POST GET DELETE;
}
}
