events { }

http {
    server {
        # Listen on all interfaces so Docker can route traffic
        listen 8080;

		client_max_body_size 1; # c'est une directive

        location / {

            root /var/www/html;
            index index.html;
			error_page 404 /errors/404.html;
			error_page 500	/errors/50x.html;

		}
    }

    # server { # c'est un contexte
    #     # Listen on all interfaces so Docker can route traffic
    #     listen 9000;

	# 	client_max_body_size 1;

    #     location / {

    #         root /var/www/html;
    #         index index.html;
	# 		error_page 404 /errors/404.html;
	# 		error_page 500	/errors/50x.html;

	# 	}
    # }
#
}
